# Form implementation generated from reading ui file 'LILYMICROJULY26.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(268, 294)
        MainWindow.setStyleSheet("QWidget {\n"
"    font: 11pt \"Poppins\";\n"
"    background:#121212;\n"
"    color:rgb(255,255,255);\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border:none;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(205,178,214);\n"
"    border-radius: 10px;\n"
"    padding:8px;\n"
"    text-align: left;\n"
"    font:10pt \"Helvetica\";\n"
"    font-weight:800;\n"
"    color: rgb(205,178,214);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QTimeEdit, QDoubleSpinBox, QSpinBox\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QDoubleSpinBox,\n"
"QSpinBox {\n"
"    border:none;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QLabel\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"    background:transparent;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QComboBox\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QComboBox {\n"
"    background-color: transparent; border:1px inset rgb(28,32,23); border-radius:2px; padding: 3px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QLineEdit\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"    QLineEdit {\n"
"    border:none;\n"
"    background: transparent;\n"
"}\n"
"QLineEdit:hover {\n"
"    border-bottom:1px solid rgba(123, 123, 123, 150);\n"
"}\n"
"QLineEdit:focus {\n"
"    border-bottom:1px solid rgba(123, 123, 123, 200);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QCheckBox\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QCheckBox::indicator {\n"
"    font-weight:bold;\n"
"    background-color: transparent;\n"
"    border: 2px solid rgb(33,143,109);\n"
"    border-radius: 6px;\n"
"    width: 8px;\n"
"    height: 8px;\n"
"    margin-left:8px;\n"
"    margin-right:8px;\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid white;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: rgb(33,143,109);\n"
"    border: 2px solid rgb(33,143,109);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider:horizontal {\n"
"    background:transparent;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 7px;\n"
"    height: 15px;\n"
"    margin: 0px;\n"
"    background:transparent;\n"
"    }\n"
"\n"
"QSlider::groove:horizontal:hover {\n"
"    background: rgb(38, 38, 38);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(255, 255, 255);\n"
"    height: 14px;\n"
"    width: 14px;\n"
"    margin: 0px;\n"
"    border-radius:7px;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background:transparent;    \n"
"    border-radius:7px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: white;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color:white;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"Time/DateEdit\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QTimeEdit,\n"
"QDateEdit {\n"
"    background-color: transparent;\n"
"    border:None;\n"
"}\n"
"\n"
"/* //////////////////////////////////////////////////////////////////////////////\n"
"QTableView\n"
"////////////////////////////////////////////////////////////////////////////// */\n"
"QTableView {\n"
"    background-color: transparent;\n"
"    alternate-background-color: rgb(101, 147, 128);\n"
"    selection-background-color: #7e57c2;\n"
"    gridline-color: rgb(90, 90, 90);color:rgb(245,245,245);\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 1px;\n"
"    background:rgb(216,79,79);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: #fff;\n"
"    background:rgb(23, 23, 23);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"#lily_mood_entry_date, #lily_diet_date, #lily_walk_date\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"#lily_diet_delete_btn,\n"
"#lily_mood_delete_btn,\n"
"#lily_walk_delete_btn {\n"
"    border:none;\n"
"    image: url(:/icons/UpdatedIcons/lily_d_norm.png);\n"
"    max-width:20px;\n"
"    min-width:20px;\n"
"    max-height:20px;\n"
"    min-height:20px;\n"
"}\n"
"#lily_diet_delete_btn:hover,\n"
"#lily_mood_delete_btn:hover,\n"
"#lily_walk_delete_btn:hover {\n"
"    image: url(:/icons/UpdatedIcons/lily_c_hover.png);\n"
"}\n"
"#lily_diet_delete_btn:pressed,\n"
"#lily_mood_delete_btn:pressed,\n"
"#lily_walk_delete_btn:pressed {\n"
"    image: url(:/icons/UpdatedIcons/lily_d_press.png);\n"
"}\n"
"\n"
"#lily_mood_entry_date,\n"
"#lily_diet_date,\n"
"#lily_walk_date {\n"
"    color:rgb(200,170,200);\n"
"}\n"
"\n"
"#lily_mood_entry_date:focus,\n"
"#lily_diet_date:focus,\n"
"#lily_walk_date:focus {\n"
"    color:#fff;\n"
"}\n"
"\n"
"/* ------------------------------------------------- \n"
"    Data // TableView nav btn frame\n"
"-------------------------------------------------  */\n"
"#lilys_data_nav_btn_frame > QPushButton {\n"
"    border-radius:3px;\n"
"    padding:2px 4px;\n"
"    border:none;\n"
"    color:#fff;\n"
"    min-width:35px;\n"
"    max-width:35px;\n"
"    min-height:35px;\n"
"    max-height:35px;\n"
"    background:transparent;\n"
"}\n"
"\n"
"#lilys_data_nav_btn_frame > QPushButton:hover {\n"
"    color:#fff;\n"
"    font-size:11pt;\n"
"    margin-top:2px;\n"
"    margin-left:2px;\n"
"    background:transparent;\n"
"    /*background-color:rgb(255,255,255); */\n"
"}\n"
"\n"
"#lilys_data_nav_btn_frame > QPushButton:checked {\n"
"    font-weight:bold;\n"
"    margin:0px;\n"
"     background:transparent;\n"
"    color:#fff;\n"
"}\n"
"\n"
"#lilys_data_nav_btn_frame > QPushButton:pressed {\n"
"    background:transparent;\n"
"    font-weight:bold;\n"
"    font-size:12pt;\n"
"    margin:0px;\n"
"    color:#fff;\n"
"}\n"
"\n"
"#lilys_data_nav_btn_frame > QPushButton:checked:hover {\n"
"    font-weight:bold;\n"
"    margin:0px;\n"
"    color:#fff;\n"
"    background:transparent;\n"
"}\n"
"\n"
"#lilys_data_nav_btn_frame > QPushButton:checked:pressed {\n"
"background:transparent;\n"
"    font-weight:bold;\n"
"    margin:0px;\n"
"    color:#fff;\n"
"}\n"
"\n"
"#lily_walk_btn,\n"
"#lily_walk_btn_2,\n"
"#lily_walk_btn_3 {\n"
"    border:none;\n"
"    max-width:35px;\n"
"    min-width:35px;\n"
"    max-height:35px;\n"
"    min-height:35px;\n"
"    image: url(:/icons/UpdatedIcons/lily_w_norm.png);\n"
"}\n"
"\n"
"#lily_walk_btn:hover,\n"
"#lily_walk_btn_2:hover,\n"
"#lily_walk_btn_3:hover {\n"
"    image: url(:/icons/UpdatedIcons/lily_w_hover.png);\n"
"}\n"
"\n"
"#lily_walk_btn:pressed,\n"
"#lily_walk_btn_2:pressed,\n"
"#lily_walk_btn_3:pressed {\n"
"    image: url(:/icons/UpdatedIcons/lily_w_press.png);\n"
"}\n"
"\n"
"#lily_ate_check_2,\n"
"#lily_ate_check {\n"
"    border:none;\n"
"    image: url(:/icons/UpdatedIcons/lily_e_norm.png);\n"
"    max-width:40px;\n"
"    min-width:40px;\n"
"    max-height:40px;\n"
"    min-height:40px;\n"
"}\n"
"\n"
"#lily_ate_check_2:hover,\n"
"#lily_ate_check:hover {\n"
"    image: url(:/icons/UpdatedIcons/lily_e_hover.png);\n"
"}\n"
"\n"
"#lily_ate_check_2:pressed,\n"
"#lily_ate_check:pressed {\n"
"    image: url(:/icons/UpdatedIcons/lily_e_press.png);\n"
"}\n"
"\n"
"#lily_ate_check_2:checked,\n"
"#lily_ate_check:checked {\n"
"    image: url(:/icons/UpdatedIcons/lilybowlchecked.png);\n"
"}\n"
"\n"
"#lily_walk_btn:checked:hover,\n"
"#lily_walk_btn_2:checked:hover,\n"
"#lily_walk_btn_3:checked:hover {\n"
"    image: url(:/icons/UpdatedIcons/lily_paw_hovered.png);\n"
"}\n"
"\n"
"#lily_walk_btn:checked:pressed,\n"
"#lily_walk_btn_2:checked:pressed,\n"
"#lily_walk_btn_3:checked:pressed {\n"
"    image: url(:/icons/UpdatedIcons/lily_paw_pressed.png);\n"
"}\n"
"\n"
"\n"
"#lily_walk_btn:checked,\n"
"#lily_walk_btn_2:checked,\n"
"#lily_walk_btn_3:checked {\n"
"    image: url(:/icons/UpdatedIcons/lilychecked.png);\n"
"}\n"
"\n"
"#lily_behavior_3,\n"
"#lily_behavior_2,\n"
"#lily_behavior {\n"
"    color:rgb(205,178,214);\n"
"}\n"
"\n"
"#lily_behavior_3:hover,\n"
"#lily_behavior_2:hover,\n"
"#lily_behavior:hover {\n"
"    color: rgb(225,198,234);\n"
"}\n"
"\n"
"#lily_behavior_3:focus,\n"
"#lily_behavior_2:focus,\n"
"#lily_behavior:focus {\n"
"    color: rgb(245,218,254);\n"
"}\n"
"\n"
"#lily_behavior_slider_3::handle:horizontal,\n"
"#lily_behavior_slider_2::handle:horizontal,\n"
"#lily_behavior_slider::handle:horizontal {\n"
"    background:rgb(160,130,160);\n"
"}\n"
"#lily_behavior_slider_3::handle:horizontal:hover,\n"
"#lily_behavior_slider_2::handle:horizontal:hover,\n"
"#lily_behavior_slider::handle:horizontal:hover {\n"
"    background:rgb(190,160,190);\n"
"}\n"
"#lily_behavior_slider_3::handle:horizontal:pressed,\n"
"#lily_behavior_slider_2::handle:horizontal:pressed,\n"
"#lily_behavior_slider::handle:horizontal:pressed {\n"
"    background:rgb(140,110,140);\n"
"}\n"
"\n"
"#lily_behavior_slider_3::groove:horizontal:hover,\n"
"#lily_behavior_slider_2::groove:horizontal:hover,\n"
"#lily_behavior_slider::groove:horizontal:hover {\n"
"    background:rgba(160,130,160,45);\n"
"}\n"
"\n"
"#lily_behavior_slider_3::groove:horizontal,\n"
"#lily_behavior_slider_2::groove:horizontal,\n"
"#lily_behavior_slider::groove:horizontal {\n"
"    background:rgba(160,130,160,45);\n"
"}\n"
"\n"
"#lily_gait,\n"
"#lily_gait_2,\n"
"#lily_gait_3 {\n"
"    color:rgb(100,70,100);\n"
"}\n"
"#lily_gait:hover,\n"
"#lily_gait_2:hover,\n"
"#lily_gait_3:hover {\n"
"    color: rgb(120,90,120);\n"
"}\n"
"#lily_gait:focus,\n"
"#lily_gait_2:focus,\n"
"#lily_gait_3:focus {\n"
"    color: rgb(140,110,140);\n"
"}\n"
"\n"
"#lily_gait_slider::handle:horizontal,\n"
"#lily_gait_slider_2::handle:horizontal,\n"
"#lily_gait_slider_3::handle:horizontal {\n"
"    background:rgb(100,70,100);\n"
"}\n"
"\n"
"#lily_gait_slider::handle:horizontal:hover,\n"
"#lily_gait_slider_2::handle:horizontal:hover,\n"
"#lily_gait_slider_3::handle:horizontal:hover {\n"
"    background:rgb(130,100,130);\n"
"}\n"
"\n"
"#lily_gait_slider::handle:horizontal:pressed,\n"
"#lily_gait_slider_2::handle:horizontal:pressed,\n"
"#lily_gait_slider_3::handle:horizontal:pressed {\n"
"    background:rgb(80,50,80);\n"
"}\n"
"\n"
"\n"
"#lily_gait_slider::groove:horizontal:hover,\n"
"#lily_gait_slider_2::groove:horizontal:hover\n"
"#lily_gait_slider_3::groove:horizontal:hover {\n"
"    background:rgba(100,70,100,45);\n"
"}\n"
"#lily_gait_slider::groove:horizontal,\n"
"#lily_gait_slider_2::groove:horizontal,\n"
"#lily_gait_slider_3::groove:horizontal {\n"
"    background:rgba(100,70,100,45);\n"
"}\n"
"\n"
"/* ------------------------------------------------- \n"
"Lilys Table Views\n"
"------------------------------------------------- */\n"
"#time_in_room_table,\n"
"#lily_diet_table,\n"
"#lily_mood_table,\n"
"#lily_walk_table,\n"
"#lily_notes_table { \n"
"    background-color: transparent;\n"
"    alternate-background-color: rgb(100, 157, 220);\n"
"    selection-background-color: #7e57c2;\n"
"    gridline-color:transparent;\n"
"    color:rgb(245,245,245);\n"
"}\n"
"#time_in_room_table::item,\n"
"#lily_diet_table::item,\n"
"#lily_mood_table::item,\n"
"#lily_walk_table::item,\n"
"#lily_notes_table::item {\n"
"    padding: 1px;\n"
"    background:rgb(180, 149, 210);\n"
"}\n"
"#lily_notes_table::item:selected,\n"
"#time_in_room_table::item:selected,\n"
"#lily_diet_table::item:selected,\n"
"#lily_mood_table::item:selected,\n"
"#lily_walk_table::item:selected {\n"
"    color: #fff;\n"
"    background:rgb(23, 23, 23);\n"
"}\n"
"\n"
"/*\n"
"LILY MOOD SLIDERS AND SPINBOXES ETC.\n"
"*/\n"
"#lily_time_in_room_slider::handle:horizontal {\n"
"    background:rgb(205,178,214);\n"
"}\n"
"#lily_time_in_room_slider::handle:horizontal:hover {\n"
"    background:rgb(235,208,244);\n"
"}\n"
"#lily_time_in_room_slider::handle:horizontal:pressed {\n"
"    background:rgb(185,158,194);\n"
"}\n"
"\n"
"#lily_time_in_room_slider::groove:horizontal:hover {\n"
"    background:rgba(205,178,214,45);\n"
"}\n"
"#lily_time_in_room_slider::groove:horizontal {\n"
"    background:rgba(205,178,214,45);\n"
"}\n"
"#lily_mood_slider::handle:horizontal {\n"
"    background:rgb(160,130,160);\n"
"}\n"
"#lily_mood_slider::handle:horizontal:hover {\n"
"    background:rgb(190,160,190);\n"
"}\n"
"#lily_mood_slider::handle:horizontal:pressed {\n"
"    background:rgb(140,110,140);\n"
"}\n"
"#lily_mood_slider::groove:horizontal:hover {\n"
"    background:rgba(160,130,160,45);\n"
"}\n"
"#lily_mood_slider::groove:horizontal {\n"
"    background:rgba(160,130,160,45);\n"
"}\n"
"#lily_mood_activity_slider::handle:horizontal {\n"
"    background:rgb(130,100,130);\n"
"}\n"
"#lily_mood_activity_slider::handle:horizontal:hover {\n"
"    background:rgb(160,130,160);\n"
"}\n"
"#lily_mood_activity_slider::handle:horizontal:pressed {\n"
"    background:rgb(110,80,110);\n"
"}\n"
"\n"
"#lily_mood_activity_slider::groove:horizontal:hover {\n"
"    background:rgba(130,100,130,45);\n"
"}\n"
"#lily_mood_activity_slider::groove:horizontal {\n"
"    background:rgba(130,100,130,45);\n"
"}\n"
"#lily_energy_slider::handle:horizontal {\n"
"    background:rgb(100,70,100);\n"
"}\n"
"\n"
"#lily_energy_slider::handle:horizontal:hover {\n"
"    background:rgb(130,100,130);\n"
"}\n"
"\n"
"#lily_energy_slider::handle:horizontal:pressed {\n"
"    background:rgb(80,50,80);\n"
"}\n"
"\n"
"#lily_energy_slider::groove:horizontal:hover {\n"
"    background:rgba(100,70,100,45);\n"
"}\n"
"#lily_energy_slider::groove:horizontal {\n"
"    background:rgba(100,70,100,45);\n"
"}\n"
"\n"
"/* Time in Room */\n"
"#lily_time_in_room {\n"
"    background:transparent;\n"
"    color:rgb(205,178,214);\n"
"}\n"
"\n"
"#lily_time_in_room:hover {\n"
"    color: rgb(225,198,234);\n"
"}\n"
"#lily_time_in_room:focus {\n"
"    color: rgb(245,218,254);\n"
"}\n"
"\n"
"/* Lily Mood */\n"
"#lily_mood {\n"
"    background:transparent;\n"
"    color:rgb(160,130,160);\n"
"}\n"
"#lily_mood:hover {\n"
"    color: rgb(180,150,180);\n"
"}\n"
"#lily_mood:focus {\n"
"    color: rgb(200,170,200);\n"
"}\n"
"\n"
"/* Lily Activity */\n"
"#lily_activity  {\n"
"    background:transparent;\n"
"    color:rgb(130,100,130);\n"
"}\n"
"#lily_activity:hover {\n"
"    color: rgb(150,120,150);\n"
"}\n"
"#lily_activity:focus {\n"
"    color: rgb(170,140,170);\n"
"}\n"
"\n"
"/* Lily Energy */\n"
"#lily_energy {\n"
"    background:transparent;\n"
"    color:rgb(100,70,100);\n"
"}\n"
"#lily_energy:hover {\n"
"    color: rgb(120,90,120);\n"
"}\n"
"#lily_energy:focus {\n"
"    color: rgb(140,110,140);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////////////////////////////\n"
"                                    QScrollBar\n"
"//////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background:transparent;\n"
"    height: 12px;\n"
"    margin: 0px 10px 0px 10px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(35,35,37);\n"
"    min-width:24px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, \n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal {\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color:transparent;\n"
"    width: 12px;\n"
"    margin: 10px 0px 10px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(35,35,37);\n"
"    min-height: 12px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, \n"
"QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(14, 16, 14, 16)
        self.gridLayout.setObjectName("gridLayout")
        self.lilyStack = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.lilyStack.setObjectName("lilyStack")
        self.lilyInputPage = QtWidgets.QWidget()
        self.lilyInputPage.setObjectName("lilyInputPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.lilyInputPage)
        self.gridLayout_2.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lily_diet_mood_input_container = QtWidgets.QFrame(parent=self.lilyInputPage)
        self.lily_diet_mood_input_container.setObjectName("lily_diet_mood_input_container")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.lily_diet_mood_input_container)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setHorizontalSpacing(6)
        self.gridLayout_15.setVerticalSpacing(3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.na_43 = QtWidgets.QLabel(parent=self.lily_diet_mood_input_container)
        self.na_43.setMaximumSize(QtCore.QSize(100, 16777215))
        self.na_43.setStyleSheet("QLabel {\n"
"font-weight:bold;\n"
"background:transparent;\n"
"color:rgb(130,100,130);\n"
"}\n"
"QLabel:hover {\n"
"color: rgb(180,160,180);\n"
"}\n"
"    ")
        self.na_43.setObjectName("na_43")
        self.gridLayout_15.addWidget(self.na_43, 10, 0, 1, 1)
        self.lily_diet_frame = QtWidgets.QFrame(parent=self.lily_diet_mood_input_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lily_diet_frame.sizePolicy().hasHeightForWidth())
        self.lily_diet_frame.setSizePolicy(sizePolicy)
        self.lily_diet_frame.setObjectName("lily_diet_frame")
        self.gridLayout_71 = QtWidgets.QGridLayout(self.lily_diet_frame)
        self.gridLayout_71.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_71.setSpacing(0)
        self.gridLayout_71.setObjectName("gridLayout_71")
        self.gridLayout_15.addWidget(self.lily_diet_frame, 1, 2, 1, 1)
        self.na_41 = QtWidgets.QLabel(parent=self.lily_diet_mood_input_container)
        self.na_41.setStyleSheet("\n"
"\n"
"QLabel {\n"
"font-weight:bold;\n"
"color:rgb(205,178,214);\n"
"}\n"
"QLabel:hover {\n"
"color: rgb(250,223,255);\n"
"}\n"
"    ")
        self.na_41.setObjectName("na_41")
        self.gridLayout_15.addWidget(self.na_41, 8, 0, 1, 1)
        self.lily_activity = QtWidgets.QSpinBox(parent=self.lily_diet_mood_input_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lily_activity.sizePolicy().hasHeightForWidth())
        self.lily_activity.setSizePolicy(sizePolicy)
        self.lily_activity.setMaximumSize(QtCore.QSize(35, 16777215))
        self.lily_activity.setStyleSheet("")
        self.lily_activity.setFrame(False)
        self.lily_activity.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lily_activity.setReadOnly(False)
        self.lily_activity.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lily_activity.setMinimum(-10)
        self.lily_activity.setMaximum(10)
        self.lily_activity.setObjectName("lily_activity")
        self.gridLayout_15.addWidget(self.lily_activity, 10, 1, 1, 1)
        self.na_46 = QtWidgets.QLabel(parent=self.lily_diet_mood_input_container)
        self.na_46.setMaximumSize(QtCore.QSize(100, 16777215))
        self.na_46.setStyleSheet("QLabel {\n"
"font-weight:bold;\n"
"background:transparent;\n"
"color:rgb(160,130,160);\n"
"}\n"
"QLabel:hover {\n"
"color: rgb(210,180,210);\n"
"}\n"
" ")
        self.na_46.setObjectName("na_46")
        self.gridLayout_15.addWidget(self.na_46, 9, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_15.addItem(spacerItem, 12, 0, 1, 4)
        self.lily_time_in_room_slider = QtWidgets.QSlider(parent=self.lily_diet_mood_input_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lily_time_in_room_slider.sizePolicy().hasHeightForWidth())
        self.lily_time_in_room_slider.setSizePolicy(sizePolicy)
        self.lily_time_in_room_slider.setStyleSheet("")
        self.lily_time_in_room_slider.setMinimum(0)
        self.lily_time_in_room_slider.setMaximum(100)
        self.lily_time_in_room_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.lily_time_in_room_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.lily_time_in_room_slider.setObjectName("lily_time_in_room_slider")
        self.gridLayout_15.addWidget(self.lily_time_in_room_slider, 8, 2, 1, 2)
        self.lily_energy_slider = QtWidgets.QSlider(parent=self.lily_diet_mood_input_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lily_energy_slider.sizePolicy().hasHeightForWidth())
        self.lily_energy_slider.setSizePolicy(sizePolicy)
        self.lily_energy_slider.setStyleSheet("")
        self.lily_energy_slider.setMinimum(0)
        self.lily_energy_slider.setMaximum(10)
        self.lily_energy_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.lily_energy_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.lily_energy_slider.setObjectName("lily_energy_slider")
        self.gridLayout_15.addWidget(self.lily_energy_slider, 11, 2, 1, 2)
        self.na_44 = QtWidgets.QLabel(parent=self.lily_diet_mood_input_container)
        self.na_44.setMaximumSize(QtCore.QSize(100, 16777215))
        self.na_44.setStyleSheet("QLabel {\n"
"font-weight:bold;\n"
"background:transparent;\n"
"color:rgb(100,70,100);\n"
"}\n"
"QLabel:hover {\n"
"color: rgb(150,120,150);\n"
"}\n"
"    ")
        self.na_44.setObjectName("na_44")
        self.gridLayout_15.addWidget(self.na_44, 11, 0, 1, 1)
        self.lily_time_in_room = QtWidgets.QSpinBox(parent=self.lily_diet_mood_input_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lily_time_in_room.sizePolicy().hasHeightForWidth())
        self.lily_time_in_room.setSizePolicy(sizePolicy)
        self.lily_time_in_room.setMaximumSize(QtCore.QSize(35, 16777215))
        self.lily_time_in_room.setStyleSheet("")
        self.lily_time_in_room.setFrame(False)
        self.lily_time_in_room.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lily_time_in_room.setReadOnly(False)
        self.lily_time_in_room.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lily_time_in_room.setMinimum(-100)
        self.lily_time_in_room.setMaximum(100)
        self.lily_time_in_room.setObjectName("lily_time_in_room")
        self.gridLayout_15.addWidget(self.lily_time_in_room, 8, 1, 1, 1)
        self.lily_energy = QtWidgets.QSpinBox(parent=self.lily_diet_mood_input_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lily_energy.sizePolicy().hasHeightForWidth())
        self.lily_energy.setSizePolicy(sizePolicy)
        self.lily_energy.setMaximumSize(QtCore.QSize(35, 16777215))
        self.lily_energy.setStyleSheet("")
        self.lily_energy.setFrame(False)
        self.lily_energy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lily_energy.setReadOnly(False)
        self.lily_energy.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lily_energy.setMinimum(-10)
        self.lily_energy.setMaximum(10)
        self.lily_energy.setObjectName("lily_energy")
        self.gridLayout_15.addWidget(self.lily_energy, 11, 1, 1, 1)
        self.lily_mood_activity_slider = QtWidgets.QSlider(parent=self.lily_diet_mood_input_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lily_mood_activity_slider.sizePolicy().hasHeightForWidth())
        self.lily_mood_activity_slider.setSizePolicy(sizePolicy)
        self.lily_mood_activity_slider.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lily_mood_activity_slider.setStyleSheet("")
        self.lily_mood_activity_slider.setMinimum(0)
        self.lily_mood_activity_slider.setMaximum(10)
        self.lily_mood_activity_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.lily_mood_activity_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.lily_mood_activity_slider.setObjectName("lily_mood_activity_slider")
        self.gridLayout_15.addWidget(self.lily_mood_activity_slider, 10, 2, 1, 2)
        self.lily_mood = QtWidgets.QSpinBox(parent=self.lily_diet_mood_input_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lily_mood.sizePolicy().hasHeightForWidth())
        self.lily_mood.setSizePolicy(sizePolicy)
        self.lily_mood.setMaximumSize(QtCore.QSize(35, 16777215))
        self.lily_mood.setStyleSheet("")
        self.lily_mood.setFrame(False)
        self.lily_mood.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lily_mood.setReadOnly(False)
        self.lily_mood.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lily_mood.setMinimum(-10)
        self.lily_mood.setMaximum(10)
        self.lily_mood.setObjectName("lily_mood")
        self.gridLayout_15.addWidget(self.lily_mood, 9, 1, 1, 1)
        self.lily_mood_slider = QtWidgets.QSlider(parent=self.lily_diet_mood_input_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lily_mood_slider.sizePolicy().hasHeightForWidth())
        self.lily_mood_slider.setSizePolicy(sizePolicy)
        self.lily_mood_slider.setStyleSheet("")
        self.lily_mood_slider.setMinimum(0)
        self.lily_mood_slider.setMaximum(10)
        self.lily_mood_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.lily_mood_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.lily_mood_slider.setObjectName("lily_mood_slider")
        self.gridLayout_15.addWidget(self.lily_mood_slider, 9, 2, 1, 2)
        self.lily_walk_note_commit_btn = QtWidgets.QPushButton(parent=self.lily_diet_mood_input_container)
        self.lily_walk_note_commit_btn.setStyleSheet("QPushButton {\n"
"border:none;\n"
"image: url(:/newPrefix/lily_walk_norm.png);\n"
"max-width:15px;\n"
"min-width:15px;\n"
"max-height:15px;\n"
"min-height:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"image: url(:/newPrefix/lily_walk_one_hover.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"image: url(:/newPrefix/lily_walk_checked_one.png);\n"
"}\n"
"\n"
"\n"
"")
        self.lily_walk_note_commit_btn.setText("")
        self.lily_walk_note_commit_btn.setIconSize(QtCore.QSize(22, 22))
        self.lily_walk_note_commit_btn.setCheckable(False)
        self.lily_walk_note_commit_btn.setObjectName("lily_walk_note_commit_btn")
        self.gridLayout_15.addWidget(self.lily_walk_note_commit_btn, 0, 3, 1, 1)
        self.lily_walk_note = QtWidgets.QLineEdit(parent=self.lily_diet_mood_input_container)
        self.lily_walk_note.setStyleSheet("\n"
"/* //////////////////////////////////////////////////////////////////////////////////////////\n"
"QComboBox Style Default\n"
"////////////////////////////////////////////////////////////////////////////////////////// */\n"
"QLineEdit {\n"
"    border:none;\n"
"    color:rgb(160,130,160);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    color: rgb(200,170,200);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color: rgb(180,150,180);\n"
"}\n"
"    ")
        self.lily_walk_note.setFrame(False)
        self.lily_walk_note.setClearButtonEnabled(False)
        self.lily_walk_note.setObjectName("lily_walk_note")
        self.gridLayout_15.addWidget(self.lily_walk_note, 0, 0, 1, 3)
        self.gridLayout_2.addWidget(self.lily_diet_mood_input_container, 3, 0, 1, 1)
        self.lily_notes = QtWidgets.QTextEdit(parent=self.lilyInputPage)
        self.lily_notes.setStyleSheet("\n"
"/* //////////////////////////////////////////////////////////////////////////////////////////\n"
"QComboBox Style Default\n"
"////////////////////////////////////////////////////////////////////////////////////////// */\n"
"QTextEdit {\n"
"    border:none;\n"
"    color:rgb(160,130,160);\n"
"}\n"
"\n"
"QTextEdit:hover {\n"
"    color: rgb(200,170,200);\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    color: rgb(180,150,180);\n"
"}\n"
"    ")
        self.lily_notes.setTabStopDistance(20.0)
        self.lily_notes.setObjectName("lily_notes")
        self.gridLayout_2.addWidget(self.lily_notes, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.button_catcher_frame = QtWidgets.QFrame(parent=self.lilyInputPage)
        self.button_catcher_frame.setObjectName("button_catcher_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_catcher_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lily_walk_btn = QtWidgets.QPushButton(parent=self.button_catcher_frame)
        self.lily_walk_btn.setStyleSheet("\n"
"QPushButton {\n"
"border:none;\n"
"image: url(:/newPrefix/lily_walk_norm.png);\n"
"max-width:30px;\n"
"min-width:30px;\n"
"max-height:30px;\n"
"min-height:30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"image: url(:/newPrefix/lily_walk_one_hover.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"image: url(:/newPrefix/lily_walk_checked_one.png);\n"
"}\n"
"\n"
"\n"
"")
        self.lily_walk_btn.setText("")
        self.lily_walk_btn.setIconSize(QtCore.QSize(22, 22))
        self.lily_walk_btn.setCheckable(False)
        self.lily_walk_btn.setObjectName("lily_walk_btn")
        self.horizontalLayout.addWidget(self.lily_walk_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lily_ate_check = QtWidgets.QPushButton(parent=self.button_catcher_frame)
        self.lily_ate_check.setStyleSheet("\n"
"QPushButton {\n"
"border:none;\n"
"image: url(:/newPrefix/lilyasdfas.png);\n"
"max-width:30px;\n"
"min-width:30px;\n"
"max-height:30px;\n"
"min-height:30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"image: url(:/newPrefix/lilydiethover2.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"image: url(:/newPrefix/lilydietchecked.png);\n"
"}\n"
"\n"
"\n"
"")
        self.lily_ate_check.setText("")
        self.lily_ate_check.setCheckable(False)
        self.lily_ate_check.setChecked(False)
        self.lily_ate_check.setFlat(True)
        self.lily_ate_check.setObjectName("lily_ate_check")
        self.horizontalLayout.addWidget(self.lily_ate_check)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout_2.addWidget(self.button_catcher_frame, 1, 0, 1, 1)
        self.walk_mood_rate_frame = QtWidgets.QFrame(parent=self.lilyInputPage)
        self.walk_mood_rate_frame.setObjectName("walk_mood_rate_frame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.walk_mood_rate_frame)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setVerticalSpacing(3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lily_behavior = QtWidgets.QSpinBox(parent=self.walk_mood_rate_frame)
        self.lily_behavior.setFrame(False)
        self.lily_behavior.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lily_behavior.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lily_behavior.setSuffix("")
        self.lily_behavior.setMinimum(0)
        self.lily_behavior.setMaximum(100)
        self.lily_behavior.setObjectName("lily_behavior")
        self.gridLayout_10.addWidget(self.lily_behavior, 1, 2, 1, 1)
        self.lily_gait = QtWidgets.QSpinBox(parent=self.walk_mood_rate_frame)
        self.lily_gait.setFrame(False)
        self.lily_gait.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lily_gait.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lily_gait.setSuffix("")
        self.lily_gait.setMinimum(0)
        self.lily_gait.setMaximum(100)
        self.lily_gait.setObjectName("lily_gait")
        self.gridLayout_10.addWidget(self.lily_gait, 2, 2, 1, 1)
        self.na_45 = QtWidgets.QLabel(parent=self.walk_mood_rate_frame)
        self.na_45.setStyleSheet("QLabel {\n"
"background:transparent;\n"
"font-weight:bold;\n"
"color:rgb(144,114,144);\n"
"}\n"
"QLabel:hover {\n"
"color:rgb(174,144,174);\n"
"}")
        self.na_45.setObjectName("na_45")
        self.gridLayout_10.addWidget(self.na_45, 2, 0, 1, 2)
        self.na_42 = QtWidgets.QLabel(parent=self.walk_mood_rate_frame)
        self.na_42.setStyleSheet("\n"
"\n"
"QLabel {\n"
"font-weight:bold;\n"
"color:rgb(205,178,214);\n"
"}\n"
"QLabel:hover {\n"
"color: rgb(250,223,255);\n"
"}\n"
"    ")
        self.na_42.setObjectName("na_42")
        self.gridLayout_10.addWidget(self.na_42, 1, 0, 1, 1)
        self.lily_behavior_slider = QtWidgets.QSlider(parent=self.walk_mood_rate_frame)
        self.lily_behavior_slider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background:rgb(205,178,214);\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background:rgb(235,208,244);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background:rgb(185,158,194);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background:rgba(205,178,214,45);\n"
"}")
        self.lily_behavior_slider.setMinimum(0)
        self.lily_behavior_slider.setMaximum(100)
        self.lily_behavior_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.lily_behavior_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.lily_behavior_slider.setObjectName("lily_behavior_slider")
        self.gridLayout_10.addWidget(self.lily_behavior_slider, 1, 3, 1, 1)
        self.lily_gait_slider = QtWidgets.QSlider(parent=self.walk_mood_rate_frame)
        self.lily_gait_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:horizontal {background:rgb(144,114,144);}\n"
"QSlider::handle:horizontal:hover {background:rgb(174,144,174);}\n"
"QSlider::handle:horizontal:pressed {background:rgb(124,94,124);}\n"
"QSlider::groove:horizontal:hover {background:rgba(144,114,144,0.25);}\n"
"")
        self.lily_gait_slider.setMinimum(0)
        self.lily_gait_slider.setMaximum(100)
        self.lily_gait_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.lily_gait_slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.lily_gait_slider.setObjectName("lily_gait_slider")
        self.gridLayout_10.addWidget(self.lily_gait_slider, 2, 3, 1, 1)
        self.gridLayout_2.addWidget(self.walk_mood_rate_frame, 2, 0, 1, 1)
        self.lily_note_commit_btn = QtWidgets.QPushButton(parent=self.lilyInputPage)
        self.lily_note_commit_btn.setStyleSheet("QPushButton {\n"
"border:none;\n"
"image: url(:/newPrefix/lily_walk_norm.png);\n"
"max-width:15px;\n"
"min-width:15px;\n"
"max-height:15px;\n"
"min-height:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"image: url(:/newPrefix/lily_walk_one_hover.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"image: url(:/newPrefix/lily_walk_checked_one.png);\n"
"}\n"
"\n"
"\n"
"")
        self.lily_note_commit_btn.setText("")
        self.lily_note_commit_btn.setIconSize(QtCore.QSize(22, 22))
        self.lily_note_commit_btn.setCheckable(False)
        self.lily_note_commit_btn.setObjectName("lily_note_commit_btn")
        self.gridLayout_2.addWidget(self.lily_note_commit_btn, 6, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lilyStack.addWidget(self.lilyInputPage)
        self.lilydataView = QtWidgets.QWidget()
        self.lilydataView.setObjectName("lilydataView")
        self.gridLayout_66 = QtWidgets.QGridLayout(self.lilydataView)
        self.gridLayout_66.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_66.setSpacing(0)
        self.gridLayout_66.setObjectName("gridLayout_66")
        self.lily_data_stack = QtWidgets.QTabWidget(parent=self.lilydataView)
        self.lily_data_stack.setStyleSheet("QTabWidget {\n"
"    background-color: #121212;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    background-color: #121212;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #121212;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #121212;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"     background-color: #121212;\n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
" background-color: #121212;\n"
"}\n"
"")
        self.lily_data_stack.setIconSize(QtCore.QSize(24, 24))
        self.lily_data_stack.setObjectName("lily_data_stack")
        self.lily_data_stackPage1 = QtWidgets.QWidget()
        self.lily_data_stackPage1.setObjectName("lily_data_stackPage1")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.lily_data_stackPage1)
        self.gridLayout_42.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_42.setSpacing(0)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.frame_35 = QtWidgets.QFrame(parent=self.lily_data_stackPage1)
        self.frame_35.setObjectName("frame_35")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.frame_35)
        self.gridLayout_43.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_43.setSpacing(0)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.frame_36 = QtWidgets.QFrame(parent=self.frame_35)
        self.frame_36.setObjectName("frame_36")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_36)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lily_walk_table = QtWidgets.QTableView(parent=self.frame_36)
        self.lily_walk_table.setStyleSheet("")
        self.lily_walk_table.setShowGrid(False)
        self.lily_walk_table.setSortingEnabled(True)
        self.lily_walk_table.setCornerButtonEnabled(False)
        self.lily_walk_table.setObjectName("lily_walk_table")
        self.lily_walk_table.horizontalHeader().setCascadingSectionResizes(True)
        self.lily_walk_table.horizontalHeader().setDefaultSectionSize(75)
        self.lily_walk_table.horizontalHeader().setMinimumSectionSize(15)
        self.lily_walk_table.horizontalHeader().setStretchLastSection(True)
        self.lily_walk_table.verticalHeader().setCascadingSectionResizes(True)
        self.lily_walk_table.verticalHeader().setSortIndicatorShown(True)
        self.gridLayout_6.addWidget(self.lily_walk_table, 1, 0, 1, 1)
        self.lily_walk_note_table = QtWidgets.QTableView(parent=self.frame_36)
        self.lily_walk_note_table.setStyleSheet("QTableView { \n"
"    background-color: transparent;\n"
"    alternate-background-color: rgb(100, 157, 220);\n"
"    selection-background-color: #7e57c2;\n"
"    gridline-color:transparent;\n"
"    color:rgb(245,245,245);\n"
"}\n"
"QTableView::item {\n"
"    padding: 1px;\n"
"    background:rgb(180, 149, 210);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: #fff;\n"
"    background:rgb(23, 23, 23);\n"
"}")
        self.lily_walk_note_table.setShowGrid(False)
        self.lily_walk_note_table.setSortingEnabled(True)
        self.lily_walk_note_table.setObjectName("lily_walk_note_table")
        self.lily_walk_note_table.horizontalHeader().setCascadingSectionResizes(True)
        self.lily_walk_note_table.horizontalHeader().setDefaultSectionSize(75)
        self.lily_walk_note_table.horizontalHeader().setMinimumSectionSize(15)
        self.lily_walk_note_table.horizontalHeader().setStretchLastSection(True)
        self.lily_walk_note_table.verticalHeader().setCascadingSectionResizes(True)
        self.lily_walk_note_table.verticalHeader().setSortIndicatorShown(True)
        self.gridLayout_6.addWidget(self.lily_walk_note_table, 1, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(parent=self.frame_36)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_6.addWidget(self.line_4, 1, 1, 1, 1)
        self.gridLayout_43.addWidget(self.frame_36, 0, 0, 1, 1)
        self.gridLayout_42.addWidget(self.frame_35, 1, 0, 1, 2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/lily_walk_norm.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/onePaw.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.lily_data_stack.addTab(self.lily_data_stackPage1, icon, "")
        self.lily_note_table_contain = QtWidgets.QWidget()
        self.lily_note_table_contain.setObjectName("lily_note_table_contain")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.lily_note_table_contain)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lily_notes_table = QtWidgets.QTableView(parent=self.lily_note_table_contain)
        self.lily_notes_table.setShowGrid(False)
        self.lily_notes_table.setSortingEnabled(True)
        self.lily_notes_table.setObjectName("lily_notes_table")
        self.lily_notes_table.horizontalHeader().setCascadingSectionResizes(True)
        self.lily_notes_table.horizontalHeader().setDefaultSectionSize(150)
        self.lily_notes_table.horizontalHeader().setMinimumSectionSize(50)
        self.lily_notes_table.horizontalHeader().setStretchLastSection(True)
        self.lily_notes_table.verticalHeader().setCascadingSectionResizes(True)
        self.lily_notes_table.verticalHeader().setSortIndicatorShown(True)
        self.gridLayout_5.addWidget(self.lily_notes_table, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/lilynotes1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/lilynoteChecked.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.lily_data_stack.addTab(self.lily_note_table_contain, icon1, "")
        self.lily_data_stackPage2 = QtWidgets.QWidget()
        self.lily_data_stackPage2.setObjectName("lily_data_stackPage2")
        self.gridLayout_55 = QtWidgets.QGridLayout(self.lily_data_stackPage2)
        self.gridLayout_55.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_55.setSpacing(0)
        self.gridLayout_55.setObjectName("gridLayout_55")
        self.frame_38 = QtWidgets.QFrame(parent=self.lily_data_stackPage2)
        self.frame_38.setObjectName("frame_38")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_38)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lily_diet_table = QtWidgets.QTableView(parent=self.frame_38)
        self.lily_diet_table.setShowGrid(False)
        self.lily_diet_table.setSortingEnabled(True)
        self.lily_diet_table.setObjectName("lily_diet_table")
        self.lily_diet_table.horizontalHeader().setCascadingSectionResizes(True)
        self.lily_diet_table.horizontalHeader().setDefaultSectionSize(150)
        self.lily_diet_table.horizontalHeader().setMinimumSectionSize(50)
        self.lily_diet_table.horizontalHeader().setStretchLastSection(True)
        self.lily_diet_table.verticalHeader().setCascadingSectionResizes(True)
        self.lily_diet_table.verticalHeader().setSortIndicatorShown(True)
        self.gridLayout_4.addWidget(self.lily_diet_table, 0, 0, 1, 1)
        self.gridLayout_55.addWidget(self.frame_38, 0, 0, 1, 2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/lilyasdfas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Mac App icon 46.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.lily_data_stack.addTab(self.lily_data_stackPage2, icon2, "")
        self.lily_data_stackPage3 = QtWidgets.QWidget()
        self.lily_data_stackPage3.setObjectName("lily_data_stackPage3")
        self.gridLayout_57 = QtWidgets.QGridLayout(self.lily_data_stackPage3)
        self.gridLayout_57.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_57.setSpacing(0)
        self.gridLayout_57.setObjectName("gridLayout_57")
        self.mood_container = QtWidgets.QFrame(parent=self.lily_data_stackPage3)
        self.mood_container.setObjectName("mood_container")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mood_container)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lily_mood_table = QtWidgets.QTableView(parent=self.mood_container)
        self.lily_mood_table.setShowGrid(False)
        self.lily_mood_table.setSortingEnabled(True)
        self.lily_mood_table.setObjectName("lily_mood_table")
        self.lily_mood_table.horizontalHeader().setCascadingSectionResizes(True)
        self.lily_mood_table.horizontalHeader().setDefaultSectionSize(150)
        self.lily_mood_table.horizontalHeader().setMinimumSectionSize(50)
        self.lily_mood_table.horizontalHeader().setStretchLastSection(True)
        self.lily_mood_table.verticalHeader().setCascadingSectionResizes(True)
        self.lily_mood_table.verticalHeader().setSortIndicatorShown(True)
        self.gridLayout_3.addWidget(self.lily_mood_table, 1, 0, 1, 1)
        self.gridLayout_57.addWidget(self.mood_container, 0, 0, 1, 2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/lily_mood_norm.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/Mac App icon 50.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.lily_data_stack.addTab(self.lily_data_stackPage3, icon3, "")
        self.lily_data_stackPage4 = QtWidgets.QWidget()
        self.lily_data_stackPage4.setObjectName("lily_data_stackPage4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.lily_data_stackPage4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.time_in_room_table = QtWidgets.QTableView(parent=self.lily_data_stackPage4)
        self.time_in_room_table.setShowGrid(False)
        self.time_in_room_table.setSortingEnabled(True)
        self.time_in_room_table.setObjectName("time_in_room_table")
        self.time_in_room_table.horizontalHeader().setCascadingSectionResizes(True)
        self.time_in_room_table.horizontalHeader().setDefaultSectionSize(150)
        self.time_in_room_table.horizontalHeader().setMinimumSectionSize(50)
        self.time_in_room_table.horizontalHeader().setStretchLastSection(True)
        self.time_in_room_table.verticalHeader().setCascadingSectionResizes(True)
        self.time_in_room_table.verticalHeader().setSortIndicatorShown(True)
        self.gridLayout_9.addWidget(self.time_in_room_table, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/roomTime2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/timeisdf.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.lily_data_stack.addTab(self.lily_data_stackPage4, icon4, "")
        self.gridLayout_66.addWidget(self.lily_data_stack, 0, 0, 1, 1)
        self.lilyStack.addWidget(self.lilydataView)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lily_date = QtWidgets.QDateEdit(parent=self.page)
        self.lily_date.setFrame(False)
        self.lily_date.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lily_date.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lily_date.setObjectName("lily_date")
        self.gridLayout_8.addWidget(self.lily_date, 0, 0, 1, 1)
        self.lily_time = QtWidgets.QTimeEdit(parent=self.page)
        self.lily_time.setStyleSheet("\n"
"QTimeEdit {\n"
"color:rgb(205,178,214);\n"
"font-size:10pt;\n"
"}\n"
"QTimeEdit:hover {\n"
"color: rgb(225,198,234);\n"
"}\n"
"QTimeEdit:focus {\n"
"color: rgb(245,218,254);\n"
"}\n"
"    ")
        self.lily_time.setFrame(False)
        self.lily_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lily_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lily_time.setObjectName("lily_time")
        self.gridLayout_8.addWidget(self.lily_time, 1, 0, 1, 1)
        self.lilyStack.addWidget(self.page)
        self.gridLayout.addWidget(self.lilyStack, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 268, 18))
        self.menubar.setObjectName("menubar")
        self.menuLily_Loves = QtWidgets.QMenu(parent=self.menubar)
        self.menuLily_Loves.setObjectName("menuLily_Loves")
        self.menuData_Op = QtWidgets.QMenu(parent=self.menubar)
        self.menuData_Op.setObjectName("menuData_Op")
        self.menuCommit = QtWidgets.QMenu(parent=self.menuData_Op)
        self.menuCommit.setObjectName("menuCommit")
        MainWindow.setMenuBar(self.menubar)
        self.action_input_page = QtGui.QAction(parent=MainWindow)
        self.action_input_page.setObjectName("action_input_page")
        self.action_data_view_page = QtGui.QAction(parent=MainWindow)
        self.action_data_view_page.setObjectName("action_data_view_page")
        self.action_commit_mood = QtGui.QAction(parent=MainWindow)
        self.action_commit_mood.setObjectName("action_commit_mood")
        self.actionMinimize = QtGui.QAction(parent=MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionMaximize = QtGui.QAction(parent=MainWindow)
        self.actionMaximize.setObjectName("actionMaximize")
        self.action_commit_room_time = QtGui.QAction(parent=MainWindow)
        self.action_commit_room_time.setObjectName("action_commit_room_time")
        self.action_delete_record = QtGui.QAction(parent=MainWindow)
        self.action_delete_record.setObjectName("action_delete_record")
        self.action_commit_lily_notes = QtGui.QAction(parent=MainWindow)
        self.action_commit_lily_notes.setObjectName("action_commit_lily_notes")
        self.actionCommit_Lily_Walk_Notes = QtGui.QAction(parent=MainWindow)
        self.actionCommit_Lily_Walk_Notes.setObjectName("actionCommit_Lily_Walk_Notes")
        self.menuLily_Loves.addAction(self.action_input_page)
        self.menuLily_Loves.addAction(self.action_data_view_page)
        self.menuLily_Loves.addAction(self.actionMinimize)
        self.menuLily_Loves.addAction(self.actionMaximize)
        self.menuCommit.addAction(self.action_commit_mood)
        self.menuCommit.addAction(self.action_commit_room_time)
        self.menuCommit.addAction(self.action_commit_lily_notes)
        self.menuCommit.addAction(self.actionCommit_Lily_Walk_Notes)
        self.menuData_Op.addAction(self.menuCommit.menuAction())
        self.menuData_Op.addAction(self.action_delete_record)
        self.menubar.addAction(self.menuLily_Loves.menuAction())
        self.menubar.addAction(self.menuData_Op.menuAction())

        self.retranslateUi(MainWindow)
        self.lilyStack.setCurrentIndex(0)
        self.lily_data_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lily_walk_table, self.lily_diet_table)
        MainWindow.setTabOrder(self.lily_diet_table, self.lily_mood_table)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.na_43.setText(_translate("MainWindow", "Lily\'s Activity"))
        self.na_41.setToolTip(_translate("MainWindow", "<html><head/><body><p>press cntrl+T to commit Time in Room Data</p></body></html>"))
        self.na_41.setText(_translate("MainWindow", "In Room"))
        self.lily_activity.setToolTip(_translate("MainWindow", "Little Lilys activity for the day, that is, her gait, her joy, her spunk :D"))
        self.na_46.setText(_translate("MainWindow", "Lily\'s Mood"))
        self.lily_time_in_room_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>press cntrl+T to commit Time in Room Data</p></body></html>"))
        self.lily_energy_slider.setToolTip(_translate("MainWindow", "Her overall energy, mostly to notice if she is acting sick"))
        self.na_44.setText(_translate("MainWindow", "Lily\'s Energy"))
        self.lily_time_in_room.setToolTip(_translate("MainWindow", "<html><head/><body><p>press cntrl+T to commit Time in Room Data</p></body></html>"))
        self.lily_energy.setToolTip(_translate("MainWindow", "Her overall energy, mostly to notice if she is acting sick"))
        self.lily_mood_activity_slider.setToolTip(_translate("MainWindow", "Little Lilys activity for the day, that is, her gait, her joy, her spunk :D"))
        self.lily_mood.setToolTip(_translate("MainWindow", "Little wiggly\'s mood for the day!"))
        self.lily_mood_slider.setToolTip(_translate("MainWindow", "Little wiggly\'s mood for the day!"))
        self.lily_walk_note_commit_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>press opt+cmd+w to commit walk data!</p></body></html>"))
        self.lily_walk_note.setPlaceholderText(_translate("MainWindow", "press the paw to commit note ➞"))
        self.lily_notes.setPlaceholderText(_translate("MainWindow", "lily\'s notes and such, use the button below to commit to the dbs! ❤ ⬇︎"))
        self.lily_walk_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>press opt+cmd+w to commit walk data!</p></body></html>"))
        self.lily_ate_check.setToolTip(_translate("MainWindow", "<html><head/><body><p>Press to <span style=\" font-style:italic;\">commit </span><span style=\" font-weight:600;\">Diet</span> Data</p></body></html>"))
        self.na_45.setText(_translate("MainWindow", "Gait"))
        self.na_42.setText(_translate("MainWindow", "Behavior"))
        self.lily_behavior_slider.setToolTip(_translate("MainWindow", "how well my lil lady \n"
"behaved, did she pull tons \n"
"or just a little?"))
        self.lily_gait_slider.setToolTip(_translate("MainWindow", "How well my lady\n"
" walked the wilds!"))
        self.lily_note_commit_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>press opt+cmd+w to commit walk data!</p></body></html>"))
        self.lily_date.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.lily_time.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.menuLily_Loves.setTitle(_translate("MainWindow", "Lily Loves "))
        self.menuData_Op.setTitle(_translate("MainWindow", "Data"))
        self.menuCommit.setTitle(_translate("MainWindow", "Commit"))
        self.action_input_page.setText(_translate("MainWindow", "Input Page"))
        self.action_input_page.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.action_data_view_page.setText(_translate("MainWindow", "Data View Page"))
        self.action_data_view_page.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.action_commit_mood.setText(_translate("MainWindow", "Commit Mood Data"))
        self.action_commit_mood.setShortcut(_translate("MainWindow", "Ctrl+Shift+M"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionMinimize.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actionMaximize.setText(_translate("MainWindow", "Maximize"))
        self.actionMaximize.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.action_commit_room_time.setText(_translate("MainWindow", "Commit Time In Room Data"))
        self.action_commit_room_time.setShortcut(_translate("MainWindow", "Ctrl+Shift+T"))
        self.action_delete_record.setText(_translate("MainWindow", "Delete Record"))
        self.action_delete_record.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.action_commit_lily_notes.setText(_translate("MainWindow", "Commit Lilys Notes"))
        self.action_commit_lily_notes.setToolTip(_translate("MainWindow", "Commit Notes to Database"))
        self.action_commit_lily_notes.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionCommit_Lily_Walk_Notes.setText(_translate("MainWindow", "Commit Lily Walk Notes"))
